name: Packages CI

on: [push]

jobs:
  gradle:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x packages-definition/gradlew
    - name: Build with Gradle
      uses: eskatos/gradle-command-action@v1
      with:
        wrapper-directory: packages-definition/gradlew
        arguments: build
    - name: Run unit tests
      run: packages-definition/gradlew test
        
